# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in lifegame-test.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "rbs", require: false
gem "steep", require: false
