# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in lifegame-test.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "1.74.0"

gem "rbs", "~> 3.0"
gem "steep", "~> 1.0"
gem "rbs-inline", "~> 0.11"
